### ISSUE TITLE
 error: narrowing conversion of ‘1.7976931348623157e+308’ from ‘double’ to ‘float’ inside { } [-Wnarrowing]

### ISSUE THREAD

**Issue by YanlinWangWang** [hguo/vortexfinder2#12]
Hi when I build this system,I find a trouble.
/home/mpi/vortexfinder/vortexfinder/src/io/Condor2Dataset.cpp:150:42: error: narrowing conversion of ‘1.7976931348623157e+308’ from ‘double’ to ‘float’ inside { } [-Wnarrowing]

This is my development environment：
ubuntu18.04 LTS cmake3.10.2 C++11 gcc7

**Comment by hguo** [comment]
Hi, 

You can try turning off libmesh support: `cmake -DWITH_LIBMESH=OFF`.  It should be off by default.  Thanks.

**Comment by YanlinWangWang** [comment]
I found that this problem is related to my compiler version and has been resolved
