### ISSUE TITLE
Data problem

### ISSUE THREAD

**Issue by YanlinWangWang** [hguo/vortexfinder2#13]
Hi! I want to run this model but lack of data. Where can I get the GLGPU simulation data. Thanks!

**Comment by hguo** [comment]
Hi, 

There is a single-timestep data in the sample_data directory.  You can follow [](https://github.com/hguo/vortexfinder2#using-the-tools) to create a file list and use the extractor_glgpu3D executable to generate results.  

Here's another way which is not documented: 

`$ extractor_glgpu3D_simple GL3D_Xfieldramp_inter_0080_cop.dat`

After the execution, you will see a text-format result GL3D_Xfieldramp_inter_0080_cop.dat.vortex in the same data directory.

**Comment by YanlinWangWang** [comment]
Thank you for your support. I have successfully run the results.
But this brings up a new question. What is the format of the .dat file and what tools can I use to open it.
And no viewer tool is generated
 Thanks again

**Comment by hguo** [comment]
Hi, 

The .dat files (BDAT format) are not in any standard format but designed by our users.  A reader is available at https://github.com/hguo/vortexfinder2/blob/master/src/io/GLGPU_IO_Helper.cpp#L177

There are two ways to visualize data: ParaView and a Qt4/OpenGL viewer.  For ParaView, you can download the official ParaView release, enable the "VortexFinder" plugins, and load the .dat file with the BDAT format in ParaView.  For the Qt/OpenGL viewer, you will need Qt4 and build with WITH_QT=ON, and run viewer1 in the command line. 

That being said, I would recommend ParaView.  The Qt/OpenGL viewer is mainly for my own debugging purpose and no longer maintained.

**Comment by YanlinWangWang** [comment]
thank you for your reply
But I have a lot of problems when using sample data

I ran ./convertor GL3D_Xfieldramp_inter_0080_cop.dat txt and found output txt is empty.
./dist GL3D_Xfieldramp_inter_0080_cop.dat  show me Usage: ./dist <dataname> <ts> <tl> <gvid0> <gvid1> <gvid2> <gvid3>
I don't understand the meaning of these parameters.
 ./extractor_glgpu3D From your example, need file which contains a list of GLGPU data file. 
Could you provide this data file or provide a method to generate the file
This will be very helpful for my research！
Thank you very much, this is my contact 2019180099wyl@bupt.edu.cn

**Comment by hguo** [comment]
I have uploaded the list file to the sample_data directory: GL3D_Xfieldramp_inter_0080_cop.dat.list.  It contains one single line of .dat filename.  You can run ./bin/extractor_glgpu3D GL3D_Xfieldramp_inter_0080_cop.dat.list and find the outputs in the same working directory.

**Comment by YanlinWangWang** [comment]
Thanks for your reply, I successfully run out.

But only one vlines file is generated. Is this correct?

I have a lot of problems when compiling the plugin.Could you please provide me with libBDATReader.dylib and libGLGPUVortexFilter.dylib files.
thank you very much

**Comment by hguo** [comment]
Yes, only one timestep is provided in the code repository. 

Re. the plugins, you can download the official ParaView release at https://www.paraview.org/, enable the "VortexFinder" plugins, and load the .dat file with the BDAT format in ParaView.  You do not have to compile your own plugins.

**Comment by YanlinWangWang** [comment]
I have installed paraview but I did not find the "VortexFinder" plugin and there is no BDATReader. Can you tell me how to find them? Thank you

**Comment by hguo** [comment]
1. Download ParaView 5.8.1 from the official website
2. Tools --> Manage Plugins.  Locate and load "VortexFinder" in Local Plugins column.  
3. Open the example data, and choose "BDAT Reader" when asked how to open the data.

**Comment by YanlinWangWang** [comment]
According to your suggestion, I successfully opened the data file. After opening, the GLGPUVortexFilter option is grayed out.Can you give me some help？

**Comment by hguo** [comment]
Click apply after opening the data.  You should be able to use the filter then.  This process is similar to other filters in ParaView; see ParaView tutorials for more details.

**Comment by YanlinWangWang** [comment]
Thanks！
