### ISSUE TITLE
When using ParaView, ParaView's protobuf libraries should be used

### ISSUE THREAD

**Issue by mathstuf** [hguo/vortexfinder2#3]
Otherwise conflicts can arise.

Cc: @tjcorona

**Comment by hguo** [comment]
Hi, 

Recently I have totally disabled protobuf in the latest version (master branch) to avoid conflicts.

**Comment by mathstuf** [comment]
OK. That should suffice (I think I figured out what I was doing differently from @tjcorona anyways).
